--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.11.2023 20:58:28
-- Server version: 8.0.31
-- Client version: 4.1
--


SET NAMES 'utf8';