--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 18.11.2023 20:58:28
-- Server version: 8.0.31
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO jobsearch.job_sites(id, site_name, registered, created, updated, archived) VALUES
(1, 'TEST1', 1, '2023-05-18 02:41:09', '2023-06-23 00:02:01', 0);